### ISSUE TITLE
this.req vs this.__req?

### ISSUE THREAD

**Issue by JetForMe** [jaredhanson/locomotive#170]
What is the difference between these two, "this.req" and "this.__req"? Various sample code I've been looking at uses both. I can't find anything in docs for locomotive, express, or node.

**Comment by JetForMe** [comment]
Sorry, this was probably better on SO, but here we are.

**Comment by jaredhanson** [comment]
Assuming you are referring to code inside a controller, they are the same.  Use of `this.req` is preferred.  Underscores indicate things used internally, and should not show up in example code.

**Comment by JetForMe** [comment]
Thanks!
