### ISSUE TITLE
Redirecting to another action?

### ISSUE THREAD

**Issue by JetForMe** [jaredhanson/locomotive#171]
I'm trying to do this in my "service" controller:

```
serviceController.edit =
function()
{
    if (!this.req.isAuthenticated())
    {
        return this.res.redirect(this.urlFor({ action: 'account/login' }));
    }

    this.user = this.req.user;
    this.render();
}
```

But I keep getting this error:

```
No route to 'service#/account#login'
```

The docs say that you can render another action’s view with a similar construct. Can I do this in an action? I can't seem to get it to work with urlFor(), anyway. Thanks.

**Comment by crispen-smith** [comment]
`this.urlFor({controller: "foo", action: "bar });`

as long as somewhere else (ideally in your router): 

`this.match("/foo/bar", "foo#bar", {as: "fooBar", action : "get"});`


Personally, I use a directory of routers and consume them all with a file module that reads all of the files in the directory and passes them into a router object.

**Comment by JetForMe** [comment]
Thanks. Kinda undoes the shortcut of being able to specify "foo#bar", huh? I managed to do it without urlFor(), just putting in the path directly. Not great, but it'll do. Thanks.

**Comment by crispen-smith** [comment]
There are times when it's really quite useful to do it this way, there are other times when using the hardcoded URL is the right call.
when urlFor gets really handy though is when you get into cases like this (admittedly contrived) example

this.match("/bands/bios/update/:band", "bandbios#update", {as: "updateBandBios" });

//In a bandbiosController action
this.redirect(this.urlFor({action: "update", band: band}));

**Comment by JetForMe** [comment]
Huh. That example implies a much more powerful mechanism than I'm aware of. One of the drawbacks of this collection of technologies is that there are no comprehensive docs, but the individual bits are generally available throughout. So it's hard to know, especially as a new user, where to look for deeper information about something you see in the getting started guide or examples.

**Comment by crispen-smith** [comment]
I haven't looked at the docs for a while, but don't discount them, there is a lot of value there.

**Comment by JetForMe** [comment]
What I mean is, it's hard to even find docs. I just recently discovered that the Readme.md files inside the modules installed by npm contain a lot of information. And the online docs for various bits differ. But none of it is comprehensive. So a technology that builds on another (say, for example, locomotive) documents its workings, but not that of what it builds on (understandably). Using locomotive as my entry point to node.js (I've done a LOT of development in Java/Spring and iOS/OS X), it's impossible to see the whole picture.

You don't know what you don't know.

It's okay, I'm making good progress on this project, just stumble occasionally.

**Comment by crispen-smith** [comment]
Take a beat to explore express.js and connect.js,  if you haven't already. These are the technologies that are those underlying technologies you're referring to in the case of locomotive.   Also, take a look at commander.js

**Comment by JetForMe** [comment]
So, one of the things that's a little unclear is how to integrate things into the locomotive convention. For example, I want to use socket.io. I ran through their example using express, but locomotive changes the way things should be initialized. I did find this (https://github.com/kayakyakr/locomotive-http-socketio-server), which seems to handle it for me, but I'm always reluctant to add dependencies to my app.

**Comment by kildem** [comment]
@JetForMe  I successfully added socketio (without adding any new dependencies/module) by removing 

    //app.phase(locomotive.boot.httpServer({ address: address, port: port })); 

in server.js and I have added a new file in the inizializer folder:

    var socketio = require('socket.io');
    var SessionSockets = require('session.socket.io');

    module.exports = function() {
      var app = this.express;
      this.msocket = socketio.listen(this.server);
      this.sessionSockets = new SessionSockets(this.msocket, this.sessionStore, this.cookieParser);
    };

then I have exposed msocket and sessionSockets variable to controller
hope this help :)

**Comment by JetForMe** [comment]
Thanks. I like that solution, except for one problem. I've noticed that my server.js (the one at the top level of my app) doesn't seem to get executed when I launch with

    $ lcm --port 8080 server

I have to use

    $ node server.js

otherwise my server.js is completely ignored. I posted a [question](http://stackoverflow.com/questions/28977137/template-provided-server-js-not-being-executed-on-app-launch) to StackOverflow about this.

**Comment by kildem** [comment]
I use node server.js to start my app, because on heroku lcm doesn't work

**Comment by JetForMe** [comment]
Interesting. Until today, I didn't even know that would work, and I'm uncomfortable that the locomotive docs tell me to use lcm but that lcm ignores server.js. Anyway, good to know it seems to be okay to launch with node.

**Comment by JetForMe** [comment]
@kildem How does your server work if you remove this line from server.js:

    //app.phase(locomotive.boot.httpServer({ address: address, port: port }));

**Comment by kildem** [comment]
I start the server on the first file in the initializers folder.
The problem is that locomotive v.4 doesn't expose this.server.
This pull request https://github.com/haxney/locomotive/commit/6020c81b95bc0016b0af63f0772f38ab3def4d30
has not been maintained in the last version of jaredhanson/locomotive

**Comment by JetForMe** [comment]
@kildem I'm a little confused. I don't have that lib/locomotive/index.js file anywhere in my locomotive app. I don't have a top-level lib dir, either. I looked at the github repo for locomotive, and can't find that file there, either.

**Comment by kildem** [comment]
it was locomotive v. 0.3
https://github.com/jaredhanson/locomotive/blob/6020c81b95bc0016b0af63f0772f38ab3def4d30/lib/locomotive/index.js

locomotive v.0.4  doesn't expose this.server.
that's why I start sever on the first file in the initialisers folder:

**Comment by JetForMe** [comment]
You do this?

    $ node config/initializers/00_generic.js

**Comment by kildem** [comment]
I mean ... the logic of starting the server is there: config/initializers/00_generic.js

    var self = this;
    require('http').createServer(app).listen(port, address, function() {
        var addr = this.address();
        console.log('listening on %s:%d', addr.address, addr.port);
        self.server = this;
        done();
    });


but I start the server:

      $ node server.js
